<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4e4609d2-e23f-49f2-9578-11f200f5e8db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;OnePlus 9 Pro 5G (Morning Mist, 8GB RAM, 128GB Storage)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acs-product-block-0']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>OnePlus 9 Pro 5G (Morning Mist, 8GB RAM, 128GB Storage)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/I/41E5Bva7sOL._AC_SX368_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/I/41E5Bva7sOL._AC_SX368_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonCarousel1&quot;)/ol[@class=&quot;a-carousel&quot;]/li[@class=&quot;a-carousel-card acswidget-carousel__card&quot;]/div[@id=&quot;acs-product-block-0&quot;]/div[@class=&quot;a-section a-spacing-mini a-spacing-top-micro acs-product-block__product-image&quot;]/a[@class=&quot;a-color-base a-link-normal&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acs-product-block-0']/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='OnePlus 9 Pro 5G (Morning Mist, 8GB RAM, 128GB Storage)']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
